<?php
/**
 * 交易咨询
 *
 * @copyright  Copyright (c) 2005-2010 ShopEx Technologies Inc. (http://www.shopex.cn)
 * @license  http://ecos.shopex.cn/ ShopEx License
 */

return array(
    'columns' => array(
        'consultation_id' => array(
            'type' => 'number',
            'autoincrement' => true,
            'required' => true,
            'comment' => app::get('sysshoppubt')->_('咨询自增编号'),
        ),
        'be_reply_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshoppubt')->_('咨询人id'),
        ),
        'user_name' => array(
            'type' => 'string',
            'label' => app::get('sysshoppubt')->_('咨询人名称'),
            'comment' => app::get('sysshoppubt')->_('咨询人名称'),
            'order' =>'2',
        ),
        'item_title' => array(
            'type' => 'string',
            'length' => 1023,
            'in_list' => true,
            'default_in_list' => true,
            'width' => '100',
            'label' => app::get('sysshoppubt')->_('交易'),
            'comment' => app::get('sysshoppubt')->_('被咨询的交易标题'),
            'order' =>'1',
        ),
        'type' => array(
            'type' => array(
                '0' => app::get('sysshoppubt')->_('标准'),
                '1' => app::get('sysshoppubt')->_('竞价'),
                '2' => app::get('sysshoppubt')->_('招标'),
            ),
            'default' => '0',
            'comment' => app::get('sysshoppubt')->_('类型'),
            'label' => app::get('sysshoppubt')->_('类型'),
            'width' => 110,
            'in_list'=>true,
            'default_in_list'=>true,
            'is_title' => true,
            'order' => 2,
        ),

        'shop_name' => array(
            'type' => 'string',
            'length' => 70,
            'width' => '70',
            'required' => true,
            'label' => app::get('sysshoppubt')->_('所属企业'),
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('sysshoppubt')->_('所属企业'),
            'filtertype' => 'has',
            'filterdefault' => true,
            'order' =>'2',
        ),
        'author' => array(
            'type' => 'string',
            'length' => 60,
            'label' => app::get('sysshoppubt')->_('操作人'),
            'width' => '40',
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('sysshoppubt')->_('操作人'),
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order' =>'3',
        ),
        'consultation_type' => array(
            'type' => array(
                'item' => '交易咨询',
                'store_delivery' => '库存/配送咨询',
                'payment' =>' 支付方式咨询',
                'invoice' => '发票保修咨询',
            ),
            'default' => 'item',
            'comment' => app::get('sysshoppubt')->_('咨询类型'),
            'label' => app::get('sysshoppubt')->_('咨询类型'),
            'filtertype' => 'yes',
            'filterdefault' => true,
            'order' =>'4',
            'width' => '40',
        ),
        'contack' => array(
            'type' => 'string',
            'length' => 200,
            'label' => app::get('sysshoppubt')->_('联系方式'),
            'width' => '20',
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('sysshoppubt')->_('联系方式'),
            'order' =>'5',
        ),
        'content' => array(
            'type' => 'string',
            'default' => '',
            'length' => 1023,
            'width' => '100',
            'label' => app::get('sysshoppubt')->_('咨询内容'),
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('sysshoppubt')->_('交易咨询的内容'),
            'filtertype' => 'has',
            'filterdefault' => true,
            'order' =>'6',
        ),
        'is_reply' => array(
            'type' => 'bool',
            'default' => '0',
            'label' => app::get('sysshoppubt')->_('是否回复'),
            'in_list' => true,
            'default_in_list' => false,
            'comment' => app::get('sysshoppubt')->_('交易咨询是否被回复'),
            'order' =>'7',
            'width' => '10',
            'filtertype' => 'bool',
            'filterdefault' => true,
        ),
        'created_time' => array(
            'type' => 'time',
            'label' => app::get('sysshoppubt')->_('咨询时间'),
            'width' => '40',
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('sysshoppubt')->_('创建时间'),
            'order' =>'8',
        ),
         'ip' => array(
            'type' => 'string',
            'label' => app::get('sysshoppubt')->_('ip'),
            'in_list' => true,
            'default_in_list' => true,
            'comment' => app::get('sysshoppubt')->_('消费者发起咨询时的ip'),
            'order' =>'11',
            'width' => '20',
        ),
        'is_display' => array(
            'type' => array('true' =>'显示','false'=>'不显示'),
            'default' => 'false',
            'label' => app::get('sysshoppubt')->_('是否显示至商祥页'),
            'comment' => app::get('sysshoppubt')->_('是否显示至商祥页'),
        ),
        'shop_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshoppubt')->_('企业ID'),
        ),
        'item_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshoppubt')->_('被咨询的交易id'),
        ),
        'author_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshoppubt')->_('操作人id'),
        ),
        'is_anonymity' => array(
            'type' => 'bool',
            'default' => 0,
            'comment' => app::get('sysshoppubt')->_('是否匿名'),
        ),
        'modified_time' => array(
            'type' => 'time',
            'label' => app::get('sysshoppubt')->_('最后修改时间'),
            'in_list' => true,
            'default_in_list' => true,
        ),
        'image_default_id' => array(
            'type' => 'string',
            'comment' => app::get('sysshoppubt')->_('交易默认图'),
        ),
    ),
    'index' => array(
        'ind_item_id' => ['columns' => ['item_id']],
        'ind_shop_id' => ['columns' => ['shop_id']],
    ),
    'primary' => 'consultation_id',
    'comment' => app::get('sysshoppubt')->_('交易咨询表'),
);
